# Generated by Django 2.1.1 on 2019-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_is_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='correct_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='current_attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='is_value_found',
            field=models.BooleanField(default=False),
        ),
    ]
